### ISSUE TITLE
#TK16: :Implementar la lógica para que el usuario pueda editar sus datos personales.

### ISSUE THREAD

**Issue by Margarita-Bravo** [GardeningFriendTeam/GardeningFriendWeb#42]

**Comment by TamiSorsaburu** [comment]
Hecho.



![Image](https://github.com/GardeningFriendTeam/GardeningFriendWeb/assets/106122755/0a4d38e7-4607-4cec-be00-497a43e39aff)



![Image](https://github.com/GardeningFriendTeam/GardeningFriendWeb/assets/106122755/bf5100ad-5599-45d6-9fa4-8153238b0b8c)




![Image](https://github.com/GardeningFriendTeam/GardeningFriendWeb/assets/106122755/aebdfd19-e314-4eb4-a295-0454320e3e9d)




![Image](https://github.com/GardeningFriendTeam/GardeningFriendWeb/assets/106122755/2a515fb0-affa-4873-b871-4302ced85352)
